services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - gitlab
    networks:
      - internal
      - external

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: git.x96.systems
    ports:
      - "22:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.x96.systems'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "postfix"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = "git.x96.systems"
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_from'] = 'gitlab@git.x96.systems'
    networks:
      - internal

  postfix:
    image: boky/postfix
    container_name: postfix
    environment:
      ALLOW_EMPTY_SENDER_DOMAINS: "yes"
      SMTP_SERVER: "postfix"
      MAILNAME: "git.x96.systems"
      SMTP_DOMAIN: "git.x96.systems"
      RELAY_MYNETWORKS: "0.0.0.0/0"
      SMTP_MYNETWORKS: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      MASQUERADE_DOMAINS: git.x96.systems
    volumes:
      - ./postfix/config:/etc/postfix
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    internal: true
  external:
    external: false
