services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: git.x96.systems
    ports:
      - "22:22" # SSH
      - "80:80" # HTTP
      - "443:443" # HTTPS
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.x96.systems'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "postfix"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['gitlab_email_from'] = 'gitlab@git.x96.systems'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['tfs@disroot.org']
        letsencrypt['auto_renew'] = true
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - internal
      - external

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - external

  postfix:
    image: boky/postfix
    container_name: postfix
    environment:
      MAILNAME: "git.x96.systems"
      SMTP_DOMAIN: "git.x96.systems"
      MASQUERADE_DOMAINS: git.x96.systems
      SMTP_MYNETWORKS: "0.0.0.0/0"
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    internal: true
  external:
    external: false
