server {
    listen 80;
    server_name git.x96.systems;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name git.x96.systems;

    ssl_certificate     /etc/letsencrypt/live/git.x96.systems/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/git.x96.systems/privkey.pem;

    location / {
        proxy_pass http://gitlab:8080;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
